const server ={
    getObject : function( arg0 ) { __ServerProxy.run('getObject', arguments); },
    createObject : function( arg0, arg1, arg2, arg3 ) { __ServerProxy.run('createObject', arguments); },
    handlingRuleExists : function( arg0, arg1 ) { __ServerProxy.run('handlingRuleExists', arguments); },
    removeRadioStream : function( arg0 ) { __ServerProxy.run('removeRadioStream', arguments); },
    resetHandlingRule : function( arg0, arg1 ) { __ServerProxy.run('resetHandlingRule', arguments); },
    getVehiclesForcedRespawnAltitude : function( ) { __ServerProxy.run('getVehiclesForcedRespawnAltitude', arguments); },
    sendGameMessageToAll : function( arg0, arg1 ) { __ServerProxy.run('sendGameMessageToAll', arguments); },
    resetWeaponDataValue : function( arg0, arg1 ) { __ServerProxy.run('resetWeaponDataValue', arguments); },
    setSpawnScreenCameraPos : function( arg0 ) { __ServerProxy.run('setSpawnScreenCameraPos', arguments); },
    setServerPassword : function( arg0 ) { __ServerProxy.run('setServerPassword', arguments); },
    sendClientMessage : function( arg0, arg1, arg2 ) { __ServerProxy.run('sendClientMessage', arguments); },
    getKillCommandDelay : function( ) { __ServerProxy.run('getKillCommandDelay', arguments); },
    setSpawnScreenCameraLookAt : function( arg0, arg1, arg2 ) { __ServerProxy.run('setSpawnScreenCameraLookAt', arguments); },
    setKillCommandDelay : function( arg0 ) { __ServerProxy.run('setKillCommandDelay', arguments); },
    removeAllKeyBinds : function( ) { __ServerProxy.run('removeAllKeyBinds', arguments); },
    getWeaponDataValue : function( arg0, arg1 ) { __ServerProxy.run('getWeaponDataValue', arguments); },
    getWastedSettings : function( ) { __ServerProxy.run('getWastedSettings', arguments); },
    resetAllVehicleHandlings : function( ) { __ServerProxy.run('resetAllVehicleHandlings', arguments); },
    setSpawnScreenPlayerPos : function( arg0 ) { __ServerProxy.run('setSpawnScreenPlayerPos', arguments); },
    setVehiclesForcedRespawnAltitude : function( arg0 ) { __ServerProxy.run('setVehiclesForcedRespawnAltitude', arguments); },
    setWastedSettings : function( arg0 ) { __ServerProxy.run('setWastedSettings', arguments); },
    showAllMapObjects : function( ) { __ServerProxy.run('showAllMapObjects', arguments); },
    setWeaponDataValue : function( arg0, arg1, arg2 ) { __ServerProxy.run('setWeaponDataValue', arguments); },
    getServerPassword : function( ) { __ServerProxy.run('getServerPassword', arguments); },
    sendClientMessageToAll : function( arg0 ) { __ServerProxy.run('sendClientMessageToAll', arguments); },
    isWeaponDataValueModified : function( arg0, arg1 ) { __ServerProxy.run('isWeaponDataValueModified', arguments); },
    resetAllWeaponData : function( ) { __ServerProxy.run('resetAllWeaponData', arguments); },
    getUnusedKeybindSlot : function( ) { __ServerProxy.run('getUnusedKeybindSlot', arguments); },
    setWorldBounds : function( arg0 ) { __ServerProxy.run('setWorldBounds', arguments); },
    isAddressBanned : function( arg0 ) { __ServerProxy.run('isAddressBanned', arguments); },
    getAllVehicles : function( ) { __ServerProxy.run('getAllVehicles', arguments); },
    getAllPlayers : function( ) { __ServerProxy.run('getAllPlayers', arguments); },
    getCheckPoint : function( arg0 ) { __ServerProxy.run('getCheckPoint', arguments); },
    getWeather : function( ) { __ServerProxy.run('getWeather', arguments); },
    getGravity : function( ) { __ServerProxy.run('getGravity', arguments); },
    getGameSpeed : function( ) { __ServerProxy.run('getGameSpeed', arguments); },
    getWaterLevel : function( ) { __ServerProxy.run('getWaterLevel', arguments); },
    getOption : function( arg0 ) { __ServerProxy.run('getOption', arguments); },
    registerKeyBind : function( arg0, arg1, arg2, arg3, arg4 ) { __ServerProxy.run('registerKeyBind', arguments); },
    setGameSpeed : function( arg0 ) { __ServerProxy.run('setGameSpeed', arguments); },
    setFallTimer : function( arg0 ) { __ServerProxy.run('setFallTimer', arguments); },
    addRadioStream : function( arg0, arg1, arg2, arg3 ) { __ServerProxy.run('addRadioStream', arguments); },
    setMinute : function( arg0 ) { __ServerProxy.run('setMinute', arguments); },
    setWaterLevel : function( arg0 ) { __ServerProxy.run('setWaterLevel', arguments); },
    getPlayer : function( arg0 ) { __ServerProxy.run('getPlayer', arguments); },
    createVehicle : function( arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 ) { __ServerProxy.run('createVehicle', arguments); },
    getVehicle : function( arg0 ) { __ServerProxy.run('getVehicle', arguments); },
    createCoordBlip : function( arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 ) { __ServerProxy.run('createCoordBlip', arguments); },
    setOption : function( arg0, arg1 ) { __ServerProxy.run('setOption', arguments); },
    playSound : function( arg0, arg1, arg2, arg3, arg4 ) { __ServerProxy.run('playSound', arguments); },
    getCoordBlipInfo : function( arg0 ) { __ServerProxy.run('getCoordBlipInfo', arguments); },
    setHour : function( arg0 ) { __ServerProxy.run('setHour', arguments); },
    getFallTimer : function( ) { __ServerProxy.run('getFallTimer', arguments); },
    addPlayerClass : function( arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12 ) { __ServerProxy.run('addPlayerClass', arguments); },
    banAddress : function( arg0 ) { __ServerProxy.run('banAddress', arguments); },
    hideMapObject : function( arg0, arg1, arg2, arg3 ) { __ServerProxy.run('hideMapObject', arguments); },
    findPlayer : function( arg0 ) { __ServerProxy.run('findPlayer', arguments); },
    setHandlingRule : function( arg0, arg1, arg2 ) { __ServerProxy.run('setHandlingRule', arguments); },
    getMinute : function( ) { __ServerProxy.run('getMinute', arguments); },
    getWorldBounds : function( ) { __ServerProxy.run('getWorldBounds', arguments); },
    unbanAddress : function( arg0 ) { __ServerProxy.run('unbanAddress', arguments); },
    resetWeaponData : function( arg0 ) { __ServerProxy.run('resetWeaponData', arguments); },
    resetHandling : function( arg0 ) { __ServerProxy.run('resetHandling', arguments); },
    setWeather : function( arg0 ) { __ServerProxy.run('setWeather', arguments); },
    createPickup : function( arg0, arg1, arg2, arg3, arg4, arg5 ) { __ServerProxy.run('createPickup', arguments); },
    showMapObject : function( arg0, arg1 ) { __ServerProxy.run('showMapObject', arguments); },
    setAltitudeLimit : function( arg0 ) { __ServerProxy.run('setAltitudeLimit', arguments); },
    getHandlingRule : function( arg0, arg1 ) { __ServerProxy.run('getHandlingRule', arguments); },
    getPickup : function( arg0 ) { __ServerProxy.run('getPickup', arguments); },
    setTimeRate : function( arg0 ) { __ServerProxy.run('setTimeRate', arguments); },
    createCheckPoint : function( arg0, arg1, arg2, arg3, arg4, arg5 ) { __ServerProxy.run('createCheckPoint', arguments); },
    createExplosion : function( arg0, arg1, arg2, arg3, arg4 ) { __ServerProxy.run('createExplosion', arguments); },
    getTimeRate : function( ) { __ServerProxy.run('getTimeRate', arguments); },
    removeKeyBind : function( arg0 ) { __ServerProxy.run('removeKeyBind', arguments); },
    setGravity : function( arg0 ) { __ServerProxy.run('setGravity', arguments); },
    getKeyBind : function( arg0 ) { __ServerProxy.run('getKeyBind', arguments); },
    destroyCoordBlip : function( arg0 ) { __ServerProxy.run('destroyCoordBlip', arguments); },
    getAltitudeLimit : function( ) { __ServerProxy.run('getAltitudeLimit', arguments); },
    getHour : function( ) { __ServerProxy.run('getHour', arguments); },
    rewireEvents : function( arg0, arg1 ) { __ServerProxy.run('rewireEvents', arguments); },
    getServerPort : function( ) { __ServerProxy.run('getServerPort', arguments); },
    isUnloaded : function( ) { __ServerProxy.run('isUnloaded', arguments); },
    setGameModeText : function( arg0 ) { __ServerProxy.run('setGameModeText', arguments); },
    reloadScript : function( ) { __ServerProxy.run('reloadScript', arguments); },
    sendScriptData : function( arg0, arg1 ) { __ServerProxy.run('sendScriptData', arguments); },
    getServerVersion : function( ) { __ServerProxy.run('getServerVersion', arguments); },
    setServerName : function( arg0 ) { __ServerProxy.run('setServerName', arguments); },
    getServerName : function( ) { __ServerProxy.run('getServerName', arguments); },
    setPlayerLimit : function( arg0 ) { __ServerProxy.run('setPlayerLimit', arguments); },
    getPlayerLimit : function( ) { __ServerProxy.run('getPlayerLimit', arguments); },
    sendGameMessage : function( arg0, arg1, arg2 ) { __ServerProxy.run('sendGameMessage', arguments); },
    getGameModeText : function( ) { __ServerProxy.run('getGameModeText', arguments); },
    shutdownServer : function( ) { __ServerProxy.run('shutdownServer', arguments); }  
    
};